const PptxGenJS = require("pptxgenjs");
const path = require("path");


async function createPresentation(slides) {


    const pptx = new PptxGenJS();


    pptx.layout = "LAYOUT_WIDE";


    pptx.author = "Voice-to-Slide";

    pptx.company = "Algoverse 2026";

    pptx.subject = "AI Generated Presentation";

    pptx.title = "Voice to Slide Deck";



    // =========================
    // TITLE SLIDE
    // =========================


    let titleSlide = pptx.addSlide();


    titleSlide.addText(
        "VOICE TO SLIDE DECK",
        {
            x:0.6,
            y:1.5,
            w:8,
            h:0.6,
            fontSize:32,
            bold:true,
            align:"center"
        }
    );


    titleSlide.addText(
        "AI Generated Presentation\nPowered by Speech + LLM",
        {
            x:1,
            y:2.3,
            w:7,
            h:1,
            fontSize:18,
            align:"center"
        }
    );


    titleSlide.addText(
        "Created for Algoverse 2026",
        {
            x:2,
            y:4.5,
            w:6,
            h:0.4,
            fontSize:14,
            align:"center"
        }
    );




    // =========================
    // CONTENT SLIDES
    // =========================


    slides.forEach((slideData,index)=>{


        const slide = pptx.addSlide();



        // Slide title

        slide.addText(
            slideData.title,
            {

                x:0.6,

                y:0.4,

                w:8,

                h:0.5,

                fontSize:26,

                bold:true

            }
        );



        // Divider line

        slide.addShape(
            pptx.ShapeType.line,
            {

                x:0.6,

                y:1,

                w:8,

                h:0

            }
        );




        let yPosition = 1.3;



        slideData.points.forEach((point)=>{


            slide.addText(
                "✓  " + point,
                {

                    x:0.8,

                    y:yPosition,

                    w:8,

                    h:0.45,

                    fontSize:18

                }
            );


            yPosition += 0.6;



        });





        // Footer

        slide.addText(
            "Generated by Voice-to-Slide AI",
            {

                x:0.5,

                y:7,

                w:5,

                h:0.3,

                fontSize:10

            }
        );



        slide.addText(
            `${index + 1}/${slides.length}`,
            {

                x:8.5,

                y:7,

                w:0.5,

                h:0.3,

                fontSize:10,

                align:"right"

            }
        );



    });





    // =========================
    // SAVE FILE
    // =========================


    const fileName = "presentation.pptx";


    const filePath = path.join(

        __dirname,

        "../downloads",

        fileName

    );



    await pptx.writeFile({

        fileName:filePath

    });



    return fileName;



}



module.exports = createPresentation;